blacklist:
  - BEDROCK
  - TNT

singleContainers:
  - HOPPER
  
doubleContainers:
  - CHEST
  - TRAPPED_CHEST

dispensers:
  - DISPENSER
  - DROPPER

opsOverrideBlacklist: false
debugMessages: false
MOARdebug: false